name: js_ui_components
description: A new Flutter package project.
version: 0.0.2+25
author: Jheime Silveira
homepage: https://github.com/jheimes-silveira/js_ui_components.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  chips_choice: ^2.0.1
  pull_to_refresh: 1.6.3
  cached_network_image: ^2.5.0
  shimmer: ^1.1.2
  flutter_spinkit: ^4.1.2+1
  octo_image: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: